from enum import Enum

class WOOCLAP_QUESTION_TYPE(Enum):
    MCQ = 1
    SORTING = 2
    MATCHING = 3
    FILLBLANK = 4

WOOCLAP_QUESTION = {
   WOOCLAP_QUESTION_TYPE.MCQ : "MCQ" ,
   WOOCLAP_QUESTION_TYPE.SORTING : "Sorting", 
   WOOCLAP_QUESTION_TYPE.MATCHING : "Matching",
   WOOCLAP_QUESTION_TYPE.FILLBLANK : "FillInTheBlanks"
}
